version: "3.9"
services:
    nginx:
        image: nginx:1.21-alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:ro
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro

    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/var/www/html
